services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ../models:/code/models
    environment:
      - MONGO_URL=mongodb://mongodb:27017/emotion_db
    depends_on:
      - mongodb

  front:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - web

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: